require("plugins")
require("colorscheme")
require("lsp")
require("treesitter")
require("options")
require("nvimtree")
require("telescope-nvim")
require("keymaps")
require("gitsigns-nvim")
require("bufferline-nvim")
require("toggleterm-nvim")
require("cscope")
require("misc")
require("lualine-nvim")
require("whichkey")
-- require("theme")

-- require("barbar-nvim")
-- require("airline")


