require("config.options")
require("config.plugins")
require("config.keymaps")

require("plugins.bufferline")
require("plugins.cscope")
require("plugins.dap")
require("plugins.gitsigns")
require("plugins.lspzero")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.misc")
require("plugins.nvimtree")
require("plugins.telescope")
require("plugins.themes")
require("plugins.toggleterm")
require("plugins.treesitter")

